name: Release Charts

on:
  push:
    branches:
      - "master"
      - "release-*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: charts/openstack-cloud-controller-manager
        env:
          CR_TOKEN: ${{ secrets.ACTION_TOKEN}}